# Generated by Django 5.2 on 2025-04-28 11:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 28, 11, 37, 56, 473830, tzinfo=datetime.timezone.utc)),
        ),
    ]
