# Generated by Django 5.2 on 2025-04-28 20:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_publish_alter_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 28, 20, 23, 22, 355970, tzinfo=datetime.timezone.utc)),
        ),
    ]
