# Generated by Django 5.2 on 2025-05-01 19:57
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_post_publish'),
    ]

    operations = [
        TrigramExtension()
    ]
